import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1765055134064 implements MigrationInterface {
    name = 'InitialSchema1765055134064'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("id" varchar PRIMARY KEY NOT NULL, "name" nvarchar(50) NOT NULL, "description" nvarchar(500), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" varchar PRIMARY KEY NOT NULL, "name" nvarchar(255) NOT NULL, "address" nvarchar(500), "phone" nvarchar(50), "email" nvarchar(255), "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_32731f181236a46182a38c992a8" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "email" nvarchar(255) NOT NULL, "passwordHash" nvarchar(255) NOT NULL, "firstName" nvarchar(100) NOT NULL, "lastName" nvarchar(100) NOT NULL, "tenantId" varchar, "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f006b5ade3eda4824fdff0785f" ON "users" ("email", "tenantId") WHERE tenantId IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("userId" varchar NOT NULL, "roleId" varchar NOT NULL, "assignedAt" datetime NOT NULL DEFAULT (datetime('now')), "assignedBy" varchar NOT NULL, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" varchar PRIMARY KEY NOT NULL, "name" nvarchar(255) NOT NULL, "description" nvarchar(1000), "tenantId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5a863c246e26467995e50b1b1f" ON "categories" ("name", "tenantId") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" varchar PRIMARY KEY NOT NULL, "name" nvarchar(255) NOT NULL, "sku" nvarchar(100) NOT NULL, "barcode" nvarchar(100), "categoryId" varchar NOT NULL, "tenantId" varchar NOT NULL, "unitPrice" decimal(18,2) NOT NULL, "costPrice" decimal(18,2), "stockQuantity" decimal(18,2) NOT NULL DEFAULT (0), "minStockLevel" decimal(18,2) NOT NULL DEFAULT (0), "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1c7c746bdf7932b41227332812" ON "products" ("barcode", "tenantId") WHERE barcode IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1b6c1ded9006ffc8e024caa715" ON "products" ("sku", "tenantId") `);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" varchar PRIMARY KEY NOT NULL, "productId" varchar NOT NULL, "tenantId" varchar NOT NULL, "movementType" nvarchar(20) NOT NULL, "quantity" decimal(18,2) NOT NULL, "unitPrice" decimal(18,2) NOT NULL, "referenceId" varchar, "notes" nvarchar(1000), "createdBy" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe8f81647152d8bfb9c7c4e490" ON "stock_movements" ("productId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "sale_items" ("id" varchar PRIMARY KEY NOT NULL, "saleId" varchar NOT NULL, "productId" varchar NOT NULL, "quantity" decimal(18,2) NOT NULL, "unitPrice" decimal(18,2) NOT NULL, "discountAmount" decimal(18,2) NOT NULL DEFAULT (0), "lineTotal" decimal(18,2) NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "saleNumber" nvarchar(50) NOT NULL, "totalAmount" decimal(18,2) NOT NULL, "discountAmount" decimal(18,2) NOT NULL DEFAULT (0), "finalAmount" decimal(18,2) NOT NULL, "paymentMethod" nvarchar(20) NOT NULL, "cashierId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e96ec22f56c541a81549f653f1" ON "sales" ("saleNumber", "tenantId") `);
        await queryRunner.query(`CREATE TABLE "temporary_user_roles" ("userId" varchar NOT NULL, "roleId" varchar NOT NULL, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`INSERT INTO "temporary_user_roles"("userId", "roleId") SELECT "userId", "roleId" FROM "user_roles"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`ALTER TABLE "temporary_user_roles" RENAME TO "user_roles"`);
        await queryRunner.query(`CREATE TABLE "temporary_user_roles" ("userId" varchar NOT NULL, "roleId" varchar NOT NULL, "assignedAt" datetime NOT NULL DEFAULT (datetime('now')), "assignedBy" varchar NOT NULL, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`INSERT INTO "temporary_user_roles"("userId", "roleId") SELECT "userId", "roleId" FROM "user_roles"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`ALTER TABLE "temporary_user_roles" RENAME TO "user_roles"`);
        await queryRunner.query(`CREATE INDEX "IDX_472b25323af01488f1f66a06b6" ON "user_roles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_86033897c009fcca8b6505d6be" ON "user_roles" ("roleId") `);
        await queryRunner.query(`DROP INDEX "IDX_f006b5ade3eda4824fdff0785f"`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "email" nvarchar(255) NOT NULL, "passwordHash" nvarchar(255) NOT NULL, "firstName" nvarchar(100) NOT NULL, "lastName" nvarchar(100) NOT NULL, "tenantId" varchar, "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_c58f7e88c286e5e3478960a998b" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "email", "passwordHash", "firstName", "lastName", "tenantId", "isActive", "createdAt", "updatedAt") SELECT "id", "email", "passwordHash", "firstName", "lastName", "tenantId", "isActive", "createdAt", "updatedAt" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f006b5ade3eda4824fdff0785f" ON "users" ("email", "tenantId") WHERE tenantId IS NOT NULL`);
        await queryRunner.query(`DROP INDEX "IDX_472b25323af01488f1f66a06b6"`);
        await queryRunner.query(`DROP INDEX "IDX_86033897c009fcca8b6505d6be"`);
        await queryRunner.query(`CREATE TABLE "temporary_user_roles" ("userId" varchar NOT NULL, "roleId" varchar NOT NULL, "assignedAt" datetime NOT NULL DEFAULT (datetime('now')), "assignedBy" varchar NOT NULL, CONSTRAINT "FK_472b25323af01488f1f66a06b67" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_86033897c009fcca8b6505d6be2" FOREIGN KEY ("roleId") REFERENCES "roles" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`INSERT INTO "temporary_user_roles"("userId", "roleId", "assignedAt", "assignedBy") SELECT "userId", "roleId", "assignedAt", "assignedBy" FROM "user_roles"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`ALTER TABLE "temporary_user_roles" RENAME TO "user_roles"`);
        await queryRunner.query(`CREATE INDEX "IDX_472b25323af01488f1f66a06b6" ON "user_roles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_86033897c009fcca8b6505d6be" ON "user_roles" ("roleId") `);
        await queryRunner.query(`DROP INDEX "IDX_5a863c246e26467995e50b1b1f"`);
        await queryRunner.query(`CREATE TABLE "temporary_categories" ("id" varchar PRIMARY KEY NOT NULL, "name" nvarchar(255) NOT NULL, "description" nvarchar(1000), "tenantId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_46a85229c9953b2b94f768190b2" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_categories"("id", "name", "description", "tenantId", "createdAt", "updatedAt") SELECT "id", "name", "description", "tenantId", "createdAt", "updatedAt" FROM "categories"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`ALTER TABLE "temporary_categories" RENAME TO "categories"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5a863c246e26467995e50b1b1f" ON "categories" ("name", "tenantId") `);
        await queryRunner.query(`DROP INDEX "IDX_1c7c746bdf7932b41227332812"`);
        await queryRunner.query(`DROP INDEX "IDX_1b6c1ded9006ffc8e024caa715"`);
        await queryRunner.query(`CREATE TABLE "temporary_products" ("id" varchar PRIMARY KEY NOT NULL, "name" nvarchar(255) NOT NULL, "sku" nvarchar(100) NOT NULL, "barcode" nvarchar(100), "categoryId" varchar NOT NULL, "tenantId" varchar NOT NULL, "unitPrice" decimal(18,2) NOT NULL, "costPrice" decimal(18,2), "stockQuantity" decimal(18,2) NOT NULL DEFAULT (0), "minStockLevel" decimal(18,2) NOT NULL DEFAULT (0), "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_6804855ba1a19523ea57e0769b4" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_products"("id", "name", "sku", "barcode", "categoryId", "tenantId", "unitPrice", "costPrice", "stockQuantity", "minStockLevel", "isActive", "createdAt", "updatedAt") SELECT "id", "name", "sku", "barcode", "categoryId", "tenantId", "unitPrice", "costPrice", "stockQuantity", "minStockLevel", "isActive", "createdAt", "updatedAt" FROM "products"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`ALTER TABLE "temporary_products" RENAME TO "products"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1c7c746bdf7932b41227332812" ON "products" ("barcode", "tenantId") WHERE barcode IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1b6c1ded9006ffc8e024caa715" ON "products" ("sku", "tenantId") `);
        await queryRunner.query(`DROP INDEX "IDX_fe8f81647152d8bfb9c7c4e490"`);
        await queryRunner.query(`CREATE TABLE "temporary_stock_movements" ("id" varchar PRIMARY KEY NOT NULL, "productId" varchar NOT NULL, "tenantId" varchar NOT NULL, "movementType" nvarchar(20) NOT NULL, "quantity" decimal(18,2) NOT NULL, "unitPrice" decimal(18,2) NOT NULL, "referenceId" varchar, "notes" nvarchar(1000), "createdBy" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_a3acb59db67e977be45e382fc56" FOREIGN KEY ("productId") REFERENCES "products" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7dde280faf0d06b5b1b067b8ac1" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_84145471dd808c370c12861afca" FOREIGN KEY ("createdBy") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_stock_movements"("id", "productId", "tenantId", "movementType", "quantity", "unitPrice", "referenceId", "notes", "createdBy", "createdAt") SELECT "id", "productId", "tenantId", "movementType", "quantity", "unitPrice", "referenceId", "notes", "createdBy", "createdAt" FROM "stock_movements"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`ALTER TABLE "temporary_stock_movements" RENAME TO "stock_movements"`);
        await queryRunner.query(`CREATE INDEX "IDX_fe8f81647152d8bfb9c7c4e490" ON "stock_movements" ("productId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "temporary_sale_items" ("id" varchar PRIMARY KEY NOT NULL, "saleId" varchar NOT NULL, "productId" varchar NOT NULL, "quantity" decimal(18,2) NOT NULL, "unitPrice" decimal(18,2) NOT NULL, "discountAmount" decimal(18,2) NOT NULL DEFAULT (0), "lineTotal" decimal(18,2) NOT NULL, CONSTRAINT "FK_c642be08de5235317d4cf3deb40" FOREIGN KEY ("saleId") REFERENCES "sales" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_d675aea38a16313e844662c48f8" FOREIGN KEY ("productId") REFERENCES "products" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_sale_items"("id", "saleId", "productId", "quantity", "unitPrice", "discountAmount", "lineTotal") SELECT "id", "saleId", "productId", "quantity", "unitPrice", "discountAmount", "lineTotal" FROM "sale_items"`);
        await queryRunner.query(`DROP TABLE "sale_items"`);
        await queryRunner.query(`ALTER TABLE "temporary_sale_items" RENAME TO "sale_items"`);
        await queryRunner.query(`DROP INDEX "IDX_e96ec22f56c541a81549f653f1"`);
        await queryRunner.query(`CREATE TABLE "temporary_sales" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "saleNumber" nvarchar(50) NOT NULL, "totalAmount" decimal(18,2) NOT NULL, "discountAmount" decimal(18,2) NOT NULL DEFAULT (0), "finalAmount" decimal(18,2) NOT NULL, "paymentMethod" nvarchar(20) NOT NULL, "cashierId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_37606c7b1560c6be428c7a48959" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3b04a33c33ed9653a8a3cd316c5" FOREIGN KEY ("cashierId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_sales"("id", "tenantId", "saleNumber", "totalAmount", "discountAmount", "finalAmount", "paymentMethod", "cashierId", "createdAt") SELECT "id", "tenantId", "saleNumber", "totalAmount", "discountAmount", "finalAmount", "paymentMethod", "cashierId", "createdAt" FROM "sales"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`ALTER TABLE "temporary_sales" RENAME TO "sales"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e96ec22f56c541a81549f653f1" ON "sales" ("saleNumber", "tenantId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_e96ec22f56c541a81549f653f1"`);
        await queryRunner.query(`ALTER TABLE "sales" RENAME TO "temporary_sales"`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "saleNumber" nvarchar(50) NOT NULL, "totalAmount" decimal(18,2) NOT NULL, "discountAmount" decimal(18,2) NOT NULL DEFAULT (0), "finalAmount" decimal(18,2) NOT NULL, "paymentMethod" nvarchar(20) NOT NULL, "cashierId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "sales"("id", "tenantId", "saleNumber", "totalAmount", "discountAmount", "finalAmount", "paymentMethod", "cashierId", "createdAt") SELECT "id", "tenantId", "saleNumber", "totalAmount", "discountAmount", "finalAmount", "paymentMethod", "cashierId", "createdAt" FROM "temporary_sales"`);
        await queryRunner.query(`DROP TABLE "temporary_sales"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e96ec22f56c541a81549f653f1" ON "sales" ("saleNumber", "tenantId") `);
        await queryRunner.query(`ALTER TABLE "sale_items" RENAME TO "temporary_sale_items"`);
        await queryRunner.query(`CREATE TABLE "sale_items" ("id" varchar PRIMARY KEY NOT NULL, "saleId" varchar NOT NULL, "productId" varchar NOT NULL, "quantity" decimal(18,2) NOT NULL, "unitPrice" decimal(18,2) NOT NULL, "discountAmount" decimal(18,2) NOT NULL DEFAULT (0), "lineTotal" decimal(18,2) NOT NULL)`);
        await queryRunner.query(`INSERT INTO "sale_items"("id", "saleId", "productId", "quantity", "unitPrice", "discountAmount", "lineTotal") SELECT "id", "saleId", "productId", "quantity", "unitPrice", "discountAmount", "lineTotal" FROM "temporary_sale_items"`);
        await queryRunner.query(`DROP TABLE "temporary_sale_items"`);
        await queryRunner.query(`DROP INDEX "IDX_fe8f81647152d8bfb9c7c4e490"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" RENAME TO "temporary_stock_movements"`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" varchar PRIMARY KEY NOT NULL, "productId" varchar NOT NULL, "tenantId" varchar NOT NULL, "movementType" nvarchar(20) NOT NULL, "quantity" decimal(18,2) NOT NULL, "unitPrice" decimal(18,2) NOT NULL, "referenceId" varchar, "notes" nvarchar(1000), "createdBy" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "stock_movements"("id", "productId", "tenantId", "movementType", "quantity", "unitPrice", "referenceId", "notes", "createdBy", "createdAt") SELECT "id", "productId", "tenantId", "movementType", "quantity", "unitPrice", "referenceId", "notes", "createdBy", "createdAt" FROM "temporary_stock_movements"`);
        await queryRunner.query(`DROP TABLE "temporary_stock_movements"`);
        await queryRunner.query(`CREATE INDEX "IDX_fe8f81647152d8bfb9c7c4e490" ON "stock_movements" ("productId", "createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_1b6c1ded9006ffc8e024caa715"`);
        await queryRunner.query(`DROP INDEX "IDX_1c7c746bdf7932b41227332812"`);
        await queryRunner.query(`ALTER TABLE "products" RENAME TO "temporary_products"`);
        await queryRunner.query(`CREATE TABLE "products" ("id" varchar PRIMARY KEY NOT NULL, "name" nvarchar(255) NOT NULL, "sku" nvarchar(100) NOT NULL, "barcode" nvarchar(100), "categoryId" varchar NOT NULL, "tenantId" varchar NOT NULL, "unitPrice" decimal(18,2) NOT NULL, "costPrice" decimal(18,2), "stockQuantity" decimal(18,2) NOT NULL DEFAULT (0), "minStockLevel" decimal(18,2) NOT NULL DEFAULT (0), "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "products"("id", "name", "sku", "barcode", "categoryId", "tenantId", "unitPrice", "costPrice", "stockQuantity", "minStockLevel", "isActive", "createdAt", "updatedAt") SELECT "id", "name", "sku", "barcode", "categoryId", "tenantId", "unitPrice", "costPrice", "stockQuantity", "minStockLevel", "isActive", "createdAt", "updatedAt" FROM "temporary_products"`);
        await queryRunner.query(`DROP TABLE "temporary_products"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1b6c1ded9006ffc8e024caa715" ON "products" ("sku", "tenantId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1c7c746bdf7932b41227332812" ON "products" ("barcode", "tenantId") WHERE barcode IS NOT NULL`);
        await queryRunner.query(`DROP INDEX "IDX_5a863c246e26467995e50b1b1f"`);
        await queryRunner.query(`ALTER TABLE "categories" RENAME TO "temporary_categories"`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" varchar PRIMARY KEY NOT NULL, "name" nvarchar(255) NOT NULL, "description" nvarchar(1000), "tenantId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "categories"("id", "name", "description", "tenantId", "createdAt", "updatedAt") SELECT "id", "name", "description", "tenantId", "createdAt", "updatedAt" FROM "temporary_categories"`);
        await queryRunner.query(`DROP TABLE "temporary_categories"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5a863c246e26467995e50b1b1f" ON "categories" ("name", "tenantId") `);
        await queryRunner.query(`DROP INDEX "IDX_86033897c009fcca8b6505d6be"`);
        await queryRunner.query(`DROP INDEX "IDX_472b25323af01488f1f66a06b6"`);
        await queryRunner.query(`ALTER TABLE "user_roles" RENAME TO "temporary_user_roles"`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("userId" varchar NOT NULL, "roleId" varchar NOT NULL, "assignedAt" datetime NOT NULL DEFAULT (datetime('now')), "assignedBy" varchar NOT NULL, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`INSERT INTO "user_roles"("userId", "roleId", "assignedAt", "assignedBy") SELECT "userId", "roleId", "assignedAt", "assignedBy" FROM "temporary_user_roles"`);
        await queryRunner.query(`DROP TABLE "temporary_user_roles"`);
        await queryRunner.query(`CREATE INDEX "IDX_86033897c009fcca8b6505d6be" ON "user_roles" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_472b25323af01488f1f66a06b6" ON "user_roles" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_f006b5ade3eda4824fdff0785f"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "email" nvarchar(255) NOT NULL, "passwordHash" nvarchar(255) NOT NULL, "firstName" nvarchar(100) NOT NULL, "lastName" nvarchar(100) NOT NULL, "tenantId" varchar, "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "users"("id", "email", "passwordHash", "firstName", "lastName", "tenantId", "isActive", "createdAt", "updatedAt") SELECT "id", "email", "passwordHash", "firstName", "lastName", "tenantId", "isActive", "createdAt", "updatedAt" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f006b5ade3eda4824fdff0785f" ON "users" ("email", "tenantId") WHERE tenantId IS NOT NULL`);
        await queryRunner.query(`DROP INDEX "IDX_86033897c009fcca8b6505d6be"`);
        await queryRunner.query(`DROP INDEX "IDX_472b25323af01488f1f66a06b6"`);
        await queryRunner.query(`ALTER TABLE "user_roles" RENAME TO "temporary_user_roles"`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("userId" varchar NOT NULL, "roleId" varchar NOT NULL, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`INSERT INTO "user_roles"("userId", "roleId") SELECT "userId", "roleId" FROM "temporary_user_roles"`);
        await queryRunner.query(`DROP TABLE "temporary_user_roles"`);
        await queryRunner.query(`ALTER TABLE "user_roles" RENAME TO "temporary_user_roles"`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("userId" varchar NOT NULL, "roleId" varchar NOT NULL, "assignedAt" datetime NOT NULL DEFAULT (datetime('now')), "assignedBy" varchar NOT NULL, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`INSERT INTO "user_roles"("userId", "roleId") SELECT "userId", "roleId" FROM "temporary_user_roles"`);
        await queryRunner.query(`DROP TABLE "temporary_user_roles"`);
        await queryRunner.query(`DROP INDEX "IDX_e96ec22f56c541a81549f653f1"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TABLE "sale_items"`);
        await queryRunner.query(`DROP INDEX "IDX_fe8f81647152d8bfb9c7c4e490"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP INDEX "IDX_1b6c1ded9006ffc8e024caa715"`);
        await queryRunner.query(`DROP INDEX "IDX_1c7c746bdf7932b41227332812"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "IDX_5a863c246e26467995e50b1b1f"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "IDX_f006b5ade3eda4824fdff0785f"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
